amazon:
  aws:
    accesskey: key
    region: us-east-1
    secretkey: ''
  dynamodb:
    endpoint: 'http://localhost:8000/'
server:
  port: 8080
spring:
  application:
    name: springboot-aws-dynamodb